import datetime
import json
import os
from Python.utilities.separate_text_stdout import SeparateText


separator = SeparateText()

# show all functionalities
# print(dir(os))

# get current working directory
print(os.getcwd())

# change current working directory
os.chdir("../text_files")
print(os.getcwd())
os.chdir("C:/Users/lazni/Desktop")
print(os.getcwd())

print(separator.separator())

# show all items in current (by default) directory
print(os.listdir())

# create a new folder
"""os.mkdir("Folder generated by python")"""

# create a new folder with possibility of nested folders <- USE THIS ONE
"""os.makedirs("Top level folder/Nested folder/Deepest folder")"""

# remove a folder                                        <- USE THIS ONE
"""os.rmdir("Folder generated by python")"""

# remove folder with specified nested ones
"""os.removedirs("Top level folder/Nested folder/Deepest folder")"""

# rename folder or file
# with open("test_textfile.txt", "w") as file: # create a file
#     pass
# print(os.listdir)
"""os.rename("test_textfile.txt", "changed_name.txt")
print(os.listdir())"""

print(separator.separator())

# look at information about files
print(os.stat("changed_name.txt"))  # print it with all attributes
print(os.stat("changed_name.txt").st_size)  # check size of the file in bytes

last_change = os.stat("changed_name.txt").st_mtime  # timestamp of last modification of file
print(datetime.datetime.fromtimestamp(last_change))

print(separator.separator())

# look at directory tree
"""os.chdir("C:/Users/lazni/PycharmProjects/Training")
for dirpath, dirnames,filenames in os.walk(os.getcwd()):
    print("current path:", dirpath)
    print("directories:", dirnames)
    print("files:", filenames, end="\n"*2)
"""

print(separator.separator())

# check environment - os.environ
"print(json.dumps(dict(os.environ), sort_keys=True, indent=4))"

# get path with separated parts (can also use it on non existing path)
path = "C:/Users/lazni/Desktop"
print(os.path.split(path))
print(os.path.dirname(path))
print(os.path.basename(path))

print(separator.separator())

# check if path or directory or file exists
print(os.path.exists(path))
print(os.path.isdir(path))
print(os.path.isfile(path))

# split file extension
print(os.path.splitext("some_path/some_file.txt"))

# run commands from cmd
# here actually open ms paint
print(os.system("mspaint"))