import random


def return_built_in_functions():
    built_in_functions = (
        "abs()",
        "all()",
        "any()",
        "ascii()",
        "bin()",
        "bool()",
        "bytearray()",
        "bytes()",
        "callable()",
        "chr()",
        "classmethod()",
        "compile()",
        "complex()",
        "delattr()",
        "dict()",
        "dir()",
        "divmod()",
        "enumerate()",
        "eval()",
        "exec()",
        "filter()",
        "float()",
        "format()",
        "frozenset()",
        "getattr()",
        "globals()",
        "hasattr()",
        "hash()",
        "help()",
        "hex()",
        "id()",
        "input()",
        "int()",
        "isinstance()",
        "issubclass()",
        "iter()",
        "len()",
        "list()",
        "locals()",
        "map()",
        "max()",
        "memoryview()",
        "min()",
        "next()",
        "object()",
        "oct()",
        "open()",
        "ord()",
        "pow()",
        "print()",
        "property()",
        "range()",
        "repr()",
        "reversed()",
        "round()",
        "set()",
        "setattr()",
        "slice()",
        "sorted()",
        "staticmethod()",
        "str()",
        "sum()",
        "super()",
        "tuple()",
        "type()",
        "vars()",
        "zip()"
    )
    for _ in range(10):
        print(random.choice(built_in_functions))
    print()


def return_string_methods():
    string_methods = (
        "capitalize()",
        "casefold()",
        "center()",
        "count()",
        "encode()",
        "endswith()",
        "expandtabs()",
        "find()",
        "format()",
        "format_map()",
        "index()",
        "isalnum()",
        "isalpha()",
        "isascii()",
        "isdecimal()",
        "isdigit()",
        "isidentifier()",
        "islower()",
        "isnumeric()",
        "isprintable()",
        "isspace()",
        "istitle()",
        "isupper()",
        "join()",
        "ljust()",
        "lower()",
        "lstrip()",
        "maketrans()",
        "partition()",
        "replace()",
        "rfind()",
        "rindex()",
        "rjust()",
        "rpartition()",
        "rsplit()",
        "rstrip()",
        "split()",
        "splitlines()",
        "startswith()",
        "strip()",
        "swapcase()",
        "title()",
        "translate()",
        "upper()",
        "zfill()"
    )
    for _ in range(10):
        print(random.choice(string_methods))


return_built_in_functions()
return_string_methods()



